# Generated by Django 5.1.6 on 2025-03-12 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_bookowned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookowned',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='books.book'),
        ),
    ]
